version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5001"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb+srv://dhruviplexustechnology:FvF0bDGv8nh3qBmI@lol.chmjk.mongodb.net/Prankster?retryWrites=true&w=majority
    command: nodemon app.js

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
